/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_team_engine_OpenVR */

#ifndef _Included_com_team_engine_OpenVR
#define _Included_com_team_engine_OpenVR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_team_engine_OpenVR
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_team_engine_OpenVR_setup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
