/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_team_engine_Engine */

#ifndef _Included_com_team_engine_Engine
#define _Included_com_team_engine_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_team_engine_Engine
 * Method:    sayHello
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_team_engine_Engine_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
